### ISSUE TITLE
Crash when browsing servers

### ISSUE THREAD

**Issue by FTC55** [TheIndra55/gtamasterserver#1]
The server seems to cause the client to crash when server browser is used.

**Comment by TheIndra55** [comment]
That's weird

Can you send my you're log?
Should be located in your Grand theft auto 5 folder and called scripthookvdotnet-(date).log

**Comment by FTC55** [comment]
I don't have access to my main pc now. I'll try to recreate the issue and send you the log later

**Comment by FTC55** [comment]
I wasn't able to recreate the issue so I'm closing it. It was most likely something temporary. Sorry for your time.
